version: '3'
services: 
  database:
    container_name: databaseproject
    build: .
    image: database
    environment: 
      MYSQL_ROOT_USER: myprojectcase
      MYSQL_ROOT_PASSWORD: myprojectcase
      MYSQL_DATABASE: sweetsweeties
    ports: 
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - "int222"

networks:
    int222:
      name: int222_network
      driver: bridge
