-- MySQL Script generated by MySQL Workbench
-- Tue Aug 24 22:18:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`customers` (
  `address` VARCHAR(1000) NULL,
  `cusFirstName` VARCHAR(400) NOT NULL,
  `customerID` INT(4) NOT NULL AUTO_INCREMENT,
  `cusUserName` VARCHAR(100) NOT NULL,
  `cusPassword` VARCHAR(8) NOT NULL,
  `email` VARCHAR(100) NULL,
  `cusPhone` INT(10) NOT NULL,
  `cusLastName` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`status` (
  `statusID` INT(4) NOT NULL,
  `sName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`statusID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `orderID` INT(4) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NOT NULL,
  `dateTime` TIMESTAMP NOT NULL,
  `customerID` INT(4) NOT NULL,
  `status_statusID` INT NOT NULL,
  PRIMARY KEY (`orderID`, `customerID`, `status_statusID`),
  INDEX `fk_order_customer1_idx` (`customerID` ASC) VISIBLE,
  INDEX `fk_order_status1_idx` (`status_statusID` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_status1`
    FOREIGN KEY (`status_statusID`)
    REFERENCES `mydb`.`status` (`statusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brands` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brands` (
  `codeBrand` INT(5) NOT NULL AUTO_INCREMENT,
  `caseBrand` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codeBrand`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sellers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sellers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sellers` (
  `sellerID` INT(4) NOT NULL,
  `selFirstName` VARCHAR(100) NOT NULL,
  `selLastName` VARCHAR(100) NOT NULL,
  `selUserName` VARCHAR(100) NOT NULL,
  `selPassword` VARCHAR(8) NOT NULL,
  `selPhone` INT(10) NOT NULL,
  PRIMARY KEY (`sellerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `caseID` INT(4) NOT NULL AUTO_INCREMENT,
  `caseName` VARCHAR(100) NOT NULL,
  `caseDescription` VARCHAR(1000) NOT NULL,
  `casePrice` FLOAT(8,2) NOT NULL,
  `caseImage` VARCHAR(1000) NOT NULL,
  `brand_CodeBrand` INT(5) NOT NULL,
  `caseDate` DATE NOT NULL,
  `brand_codeBrand` INT(5) NOT NULL,
  `seller_sellerID` INT(4) NOT NULL,
  PRIMARY KEY (`caseID`, `brand_codeBrand`, `seller_sellerID`),
  INDEX `fk_products_brand1_idx` (`brand_codeBrand` ASC) VISIBLE,
  INDEX `fk_products_seller1_idx` (`seller_sellerID` ASC) VISIBLE,
  CONSTRAINT `fk_products_brand1`
    FOREIGN KEY (`brand_codeBrand`)
    REFERENCES `mydb`.`brands` (`codeBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_seller1`
    FOREIGN KEY (`seller_sellerID`)
    REFERENCES `mydb`.`sellers` (`sellerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`colors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`colors` (
  `codeColor` INT(5) NOT NULL AUTO_INCREMENT,
  `caseColor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codeColor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orderdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orderdetail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orderdetail` (
  `quanityOrder` INT(4) NOT NULL,
  `unitPrice` FLOAT(12,2) NOT NULL,
  `order_orderId` INT(4) NOT NULL,
  `products_caseId` INT(4) NOT NULL,
  PRIMARY KEY (`order_orderId`, `products_caseId`),
  INDEX `fk_orderdetail_products1_idx` (`products_caseId` ASC) VISIBLE,
  CONSTRAINT `fk_orderdetail_order1`
    FOREIGN KEY (`order_orderId`)
    REFERENCES `mydb`.`orders` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetail_products1`
    FOREIGN KEY (`products_caseId`)
    REFERENCES `mydb`.`products` (`caseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`products_has_color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products_has_color` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products_has_color` (
  `products_caseId` INT(4) NOT NULL,
  `color_codeColor` INT(5) NOT NULL,
  PRIMARY KEY (`products_caseId`, `color_codeColor`),
  INDEX `fk_products_has_color_color1_idx` (`color_codeColor` ASC) VISIBLE,
  INDEX `fk_products_has_color_products1_idx` (`products_caseId` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_color_products1`
    FOREIGN KEY (`products_caseId`)
    REFERENCES `mydb`.`products` (`caseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_color_color1`
    FOREIGN KEY (`color_codeColor`)
    REFERENCES `mydb`.`colors` (`codeColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`payments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`payments` (
  `amount` FLOAT(12,2) NOT NULL,
  `paymentID` INT(4) NOT NULL AUTO_INCREMENT,
  `paymentDate` DATE NOT NULL,
  `customerID` INT(4) NOT NULL,
  PRIMARY KEY (`paymentID`, `customerID`),
  INDEX `fk_payments_customer1_idx` (`customerID` ASC) VISIBLE,
  CONSTRAINT `fk_payments_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`models` ;

CREATE TABLE IF NOT EXISTS `mydb`.`models` (
  `modelID` INT(4) NOT NULL AUTO_INCREMENT,
  `modelName` VARCHAR(100) NOT NULL,
  `brand_codeBrand` INT(5) NOT NULL,
  PRIMARY KEY (`modelID`, `brand_codeBrand`),
  INDEX `fk_model_brand1_idx` (`brand_codeBrand` ASC) VISIBLE,
  CONSTRAINT `fk_model_brand1`
    FOREIGN KEY (`brand_codeBrand`)
    REFERENCES `mydb`.`brands` (`codeBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
